command:
  - streamlit
  - run
  - app.py

env:
  - name: DATABRICKS_JOB_ID
    value: "600311442506437"

resources:
  - name: sql-warehouse
    sql_warehouse:
      id: "0e6bd176c827b16a"
      permission: CAN_USE
